#!/usr/bin/env bash

       #===========================================#
      #     ____             __                   #
     #     / __ )____ ______/ /_  __________     #
    #     / __  / __ `/ ___/ __ \/ ___/ ___/    #
   #   _ / /_/ / /_/ (__  ) / / / /  / /__     #
  #   (_)_____/\__,_/____/_/ /_/_/   \___/    #
 #                                           #
#===========================================#
# The main bash config file. Bash originates from sh, which is not another
# shell, but a POSIX standard. For example /bin/sh actually points to a dash
# implementation on all Ubuntu systems. Bash incudes some extra features on top
# of sh to make it a little bit more "programmable" (these are usually refered
# to as bashisms).
#
# The bashrc contains all config for non-login interactive bash sessions. For
# login sessions, see the .bash_profile instead.

export XDG_CONFIG_HOME=~/.config

config="${XDG_CONFIG_HOME}"
base="$config/dots"
platform=$(uname)

  #======#
 # Path #
#======#

# Add things to the PATH here
export PATH=~/bin:\
~/.cargo/bin:\
/usr/local/bin:\
/usr/local/opt/python/libexec/bin:\
$PATH

export RUST_SRC_PATH=/usr/local/src/rust/src

if [ "$platform" == "Darwin" ]; then

export PATH=/usr/local/opt/coreutils/libexec/gnubin:\
$PATH

export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:\
$MANPATH

fi

  #======================#
 # Personal Preferences #
#======================#

reset=$(tput sgr0)
bold=$(tput bold)
dim=$'\e[2m'
italic=$'\e[3m'
newline=$'\n'
black=$(tput setaf 0)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)

zsh_prompt () {
  local bar="${magenta}▍ ${reset}"
  local name_and_host="${bold}%n@%m${reset}"
  local path="%2d"
  local pointer="»"
  PS1="${newline}${bar}${name_and_host}${newline}${bar}${path}${pointer} "
}

bash_prompt () { 
  PROMPT_DIRTRIM=2 # only display two directories with \w
  local bar="${magenta}▍ ${reset}"
  local name_and_host="${bold}\u@\h${reset}"
  local path="\w"
  local pointer="»"
  PS1="${newline}${bar}${name_and_host}${newline}${bar}${path}${pointer} "
}

if [ -n "$ZSH_VERSION" ]; then
  zsh_prompt
elif [ -n "$BASH_VERSION" ]; then
  bash_prompt
fi

  #=============#
 # Environment #
#=============#

export GIT_EDITOR=vim
export EDITOR=vim

  #=================#
 # Helpful Scripts #
#=================#

eval "$(projects init)";
exists() { command -v "$1" >/dev/null 2>&1; }
weather() { curl -4 http://wttr.in/"$1"; }

  #=========#
 # Aliases #
#=========#

if exists nvim; then
  alias vim="nvim"
  alias vi="nvim"
fi

if exists hub; then
  eval "$(hub alias -s)"
fi

  #============#
 # Other Dots #
#============#

if exists dots; then
  if private_dots=$(dots prefix webdesserts-private); then
    source $private_dots/bashrc.work
  fi
fi
