[package]
name = "webdesserts"
authors = [ "Michael Mullins <michael@webdesserts.com>" ]

[link]
"shell/bashrc" = "~/.bashrc"
"shell/bash_profile" = "~/.bash_profile"
"shell/zshrc" = "~/.zshrc"
"shell/zprofile" = "~/.zprofile"
"shell/env.nu" = "~/Library/Application Support/nushell/env.nu"
"shell/config.nu" = "~/Library/Application Support/nushell/config.nu"
"scripts" = "~/scripts"
"git/config" = "~/.config/git/config"
"git/config_webdesserts" = "~/.config/git/config_webdesserts"
"editorconfig" = "~/.editorconfig"
"vscode_settings.jsonc" = "~/Library/Application Support/Code/User/settings.json"
"vscode_keybindings.jsonc" = "~/Library/Application Support/Code/User/keybindings.json"
"sysctl.conf" = "/etc/sysctl.conf"