[package]
name = "webdesserts"
authors = [ "Michael Mullins <michael@webdesserts.com>" ]

[link]
bashrc = "~/.bashrc"
bash_profile = "~/.bash_profile"
editorconfig = "~/.editorconfig"
"git/config" = "~/.config/git/config"
"git/config_webdesserts" = "~/.config/git/config_webdesserts"
"vscode_settings.jsonc" = "~/Library/Application Support/Code/User/settings.json"
"vscode_keybindings.jsonc" = "~/Library/Application Support/Code/User/keybindings.json"
"sysctl.conf" = "/etc/sysctl.conf"
"bin/exists" = "~/bin/exists"
"bin/vscode" = "~/bin/vscode"