[package]
name = "webdesserts"
authors = ["Michael Mullins <michael@webdesserts.com>"]

[link]
"~/.bashrc" = "shell/bashrc"
"~/.bash_profile" = "shell/bash_profile"
"~/.zshrc" = "shell/zshrc"
"~/.zprofile" = "shell/zprofile"
"~/Library/Application Support/nushell/env.nu" = "shell/env.nu"
"~/Library/Application Support/nushell/config.nu" = "shell/config.nu"
"~/scripts/externs.nu" = "scripts/externs.nu"
"~/scripts/prompts.nu" = "scripts/prompts.nu"
"~/scripts/themes.nu" = "scripts/themes.nu"
"~/scripts/utils.nu" = "scripts/utils.nu"
"~/scripts/vscode.nu" = "scripts/vscode.nu"
"~/scripts/personal.nu" = "scripts/personal.nu"
"~/scripts/atlassian.nu" = "scripts/atlassian.nu"
"~/.config/git/config" = "git/config"
"~/.config/git/config_webdesserts" = "git/config_webdesserts"
"~/.editorconfig" = "editorconfig"
"~/Library/Application Support/Code/User/settings.json" = "vscode_settings.jsonc"
"~/Library/Application Support/Code/User/keybindings.json" = "vscode_keybindings.jsonc"
"~/.claude/CLAUDE.md" = "claude/CLAUDE.md"
"~/.claude/settings.json" = "claude/settings.json"
"/etc/sysctl.conf" = "sysctl.conf"
